# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compubapi_v1/AttributeMigration.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%compubapi_v1/AttributeMigration.proto\x12\x16yoti.core.compubapi_v1\"2\n\x19\x41ttributeMigrationPayload\x12\x15\n\rattribute_ids\x18\x01 \x03(\x0c\x42t\n\x15\x63om.yoti.compubapi_v1B\x1e\x41ttributeMigrationPayloadProtoZ,go.internal.yoti.com/proto/core/compubapi_v1\xba\x02\x0c\x43ompubapiV1_b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AttributeMigration_pb2.py', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025com.yoti.compubapi_v1B\036AttributeMigrationPayloadProtoZ,go.internal.yoti.com/proto/core/compubapi_v1\272\002\014CompubapiV1_'
  _ATTRIBUTEMIGRATIONPAYLOAD._serialized_start=65
  _ATTRIBUTEMIGRATIONPAYLOAD._serialized_end=115
# @@protoc_insertion_point(module_scope)
