# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: encrypted_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='encrypted_data.proto',
  package='compubapi_v1',
  syntax='proto3',
  serialized_pb=_b('\n\x14\x65ncrypted_data.proto\x12\x0c\x63ompubapi_v1\"0\n\rEncryptedData\x12\n\n\x02iv\x18\x01 \x01(\x0c\x12\x13\n\x0b\x63ipher_text\x18\x02 \x01(\x0c\x42+\n\x15\x63om.yoti.compubapi_v1B\x12\x45ncryptedDataProtob\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ENCRYPTEDDATA = _descriptor.Descriptor(
  name='EncryptedData',
  full_name='compubapi_v1.EncryptedData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iv', full_name='compubapi_v1.EncryptedData.iv', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cipher_text', full_name='compubapi_v1.EncryptedData.cipher_text', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=86,
)

DESCRIPTOR.message_types_by_name['EncryptedData'] = _ENCRYPTEDDATA

EncryptedData = _reflection.GeneratedProtocolMessageType('EncryptedData', (_message.Message,), dict(
  DESCRIPTOR = _ENCRYPTEDDATA,
  __module__ = 'encrypted_data_pb2'
  # @@protoc_insertion_point(class_scope:compubapi_v1.EncryptedData)
  ))
_sym_db.RegisterMessage(EncryptedData)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\025com.yoti.compubapi_v1B\022EncryptedDataProto'))
# @@protoc_insertion_point(module_scope)
