# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signed_timestamp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='signed_timestamp.proto',
  package='compubapi_v1',
  syntax='proto3',
  serialized_pb=_b('\n\x16signed_timestamp.proto\x12\x0c\x63ompubapi_v1\"\x9b\x01\n\x0fSignedTimestamp\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x16\n\x0emessage_digest\x18\x03 \x01(\x0c\x12\x14\n\x0c\x63hain_digest\x18\x04 \x01(\x0c\x12\x1a\n\x12\x63hain_digest_skip1\x18\x05 \x01(\x0c\x12\x1a\n\x12\x63hain_digest_skip2\x18\x06 \x01(\x0c\x42-\n\x15\x63om.yoti.compubapi_v1B\x14SignedTimestampProtob\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SIGNEDTIMESTAMP = _descriptor.Descriptor(
  name='SignedTimestamp',
  full_name='compubapi_v1.SignedTimestamp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='compubapi_v1.SignedTimestamp.version', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='compubapi_v1.SignedTimestamp.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message_digest', full_name='compubapi_v1.SignedTimestamp.message_digest', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chain_digest', full_name='compubapi_v1.SignedTimestamp.chain_digest', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chain_digest_skip1', full_name='compubapi_v1.SignedTimestamp.chain_digest_skip1', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='chain_digest_skip2', full_name='compubapi_v1.SignedTimestamp.chain_digest_skip2', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=196,
)

DESCRIPTOR.message_types_by_name['SignedTimestamp'] = _SIGNEDTIMESTAMP

SignedTimestamp = _reflection.GeneratedProtocolMessageType('SignedTimestamp', (_message.Message,), dict(
  DESCRIPTOR = _SIGNEDTIMESTAMP,
  __module__ = 'signed_timestamp_pb2'
  # @@protoc_insertion_point(class_scope:compubapi_v1.SignedTimestamp)
  ))
_sym_db.RegisterMessage(SignedTimestamp)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\025com.yoti.compubapi_v1B\024SignedTimestampProto'))
# @@protoc_insertion_point(module_scope)
