# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: devicepubapi_v1/StaticCredentialAuth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*devicepubapi_v1/StaticCredentialAuth.proto\x12\x19yoti.core.devicepubapi_v1\"\x16\n\x14StaticCredentialAuthb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'StaticCredentialAuth_pb2.py', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = None
  _STATICCREDENTIALAUTH._serialized_start=73
  _STATICCREDENTIALAUTH._serialized_end=95
# @@protoc_insertion_point(module_scope)
