# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sharepubapi_v1/SessionData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n sharepubapi_v1/SessionData.proto\x12\x18yoti.core.sharepubapi_v1\"L\n\x0bSessionData\x12\x11\n\trandom_id\x18\x01 \x01(\t\x12\x15\n\rdatacentre_id\x18\x02 \x01(\t\x12\x13\n\x0binstance_id\x18\x03 \x01(\tBl\n\x17\x63om.yoti.sharepubapi_v1B\x10SessionDataProtoZ.go.internal.yoti.com/proto/core/sharepubapi_v1\xba\x02\x0eSharepubapiV1_b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SessionData_pb2.py', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.yoti.sharepubapi_v1B\020SessionDataProtoZ.go.internal.yoti.com/proto/core/sharepubapi_v1\272\002\016SharepubapiV1_'
  _SESSIONDATA._serialized_start=62
  _SESSIONDATA._serialized_end=138
# @@protoc_insertion_point(module_scope)
