from setuptools import setup, find_packages

setup(
    name="your_package_name",  # Replace with your actual package name
    version="your_package_version",  # Replace with your actual package version
    packages=find_packages(),
    install_requires=[
        "deprecated==1.2.10",  
        "cryptography==44.0.2",  
        "protobuf==4.25.3",  
        "requests==2.32.3",  
        "future==0.18.3",  
        "asn1==2.2.0",
        "pyopenssl==25.0.0",  
        "iso8601==0.1.14",  
        "wheel==0.43.0",  
        "pytz==2024.1",  
        "cffi==1.17.1",
        "charset-normalizer==3.4.1",
        "idna==2.7",
        "urllib3==2.3.0",
        "six==1.16.0",
        "wrapt==1.17.2",
    ],
    extras_require={
        "examples": [
            "Django>=3.0.7",
            "Flask>=1.0.4",
            "python-dotenv>=0.7.1",
            "django-sslserver>=0.22.0",
            "Werkzeug==2.1.2",
        ],
        "dev": [
            "pre-commit==2.16.0",
            "pytest>=4.6.11",
            "pytest-cov>=2.7.1",
            "pylint==1.9.4",
            "pylint-exit>=1.1.0",
            "python-coveralls==2.9.3",
            "coverage==4.5.4",
            "mock==2.0.0",
            "virtualenv==20.15.1",
            "flake8==4.0.1",
            "pip-tools==6.6.2",
        ],
    },
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Intended Audience :: Developers",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    keywords="yoti sdk 2FA multifactor authentication verification identity login register verify 2Factor",
)