# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import iso8601
from iso8601 import ParseError

from yoti_python_sdk.doc_scan import constants
from yoti_python_sdk.doc_scan.session.retrieve.resource_response import ResourceResponse
from yoti_python_sdk.doc_scan.session.retrieve.file_response import FileResponse
from yoti_python_sdk.doc_scan.session.retrieve.media_response import MediaResponse


class ShareCodeProfile(object):
    """
    Represents a share code profile (lookup or returned)
    """

    def __init__(self, data=None):
        """
        :param data: the data to parse
        :type data: dict or None
        """
        if data is None:
            data = dict()

        self.__media = MediaResponse(data["media"]) if "media" in data.keys() else None

    @property
    def media(self):
        """
        Returns the media associated with the profile

        :return: the media
        :rtype: MediaResponse or None
        """
        return self.__media


class ShareCodeIdPhoto(object):
    """
    Represents a share code ID photo
    """

    def __init__(self, data=None):
        """
        :param data: the data to parse
        :type data: dict or None
        """
        if data is None:
            data = dict()

        self.__media = MediaResponse(data["media"]) if "media" in data.keys() else None

    @property
    def media(self):
        """
        Returns the media associated with the ID photo

        :return: the media
        :rtype: MediaResponse or None
        """
        return self.__media


class VerifyShareCodeTaskResponse(object):
    """
    Represents a verify share code task
    """

    def __init__(self, data=None):
        """
        :param data: the data to parse
        :type data: dict or None
        """
        if data is None:
            data = dict()

        self.__type = data.get("type", None)
        self.__id = data.get("id", None)
        self.__state = data.get("state", None)
        self.__created = self.__parse_date(data.get("created", None))
        self.__last_updated = self.__parse_date(data.get("last_updated", None))
        
        from yoti_python_sdk.doc_scan.session.retrieve.generated_media import GeneratedMedia
        self.__generated_media = [
            GeneratedMedia(media) for media in data.get("generated_media", [])
        ]

    @staticmethod
    def __parse_date(date):
        """
        Parse a date using the iso8601 library,
        returning None if there was an error

        :param date: the date string to parse
        :type date: str
        :return: the parsed date
        :rtype: datetime.datetime or None
        """
        if date is None:
            return None

        try:
            return iso8601.parse_date(date)
        except ParseError:
            return None

    @property
    def type(self):
        """
        Return the type of the task

        :return: the type
        :rtype: str or None
        """
        return self.__type

    @property
    def id(self):
        """
        Return the ID of the task

        :return: the ID
        :rtype: str or None
        """
        return self.__id

    @property
    def state(self):
        """
        Return the state of the task

        :return: the state
        :rtype: str or None
        """
        return self.__state

    @property
    def created(self):
        """
        Return the date the task was created

        :return: the created date
        :rtype: datetime.datetime or None
        """
        return self.__created

    @property
    def last_updated(self):
        """
        Return the date the task was last updated

        :return: the last updated date
        :rtype: datetime.datetime or None
        """
        return self.__last_updated

    @property
    def generated_media(self):
        """
        Return the list of media that has been generated by the task

        :return: the list of generated media
        :rtype: list[GeneratedMedia]
        """
        return self.__generated_media


class ShareCodeResourceResponse(ResourceResponse):
    """
    Represents a share code resource for a given session
    """

    def __init__(self, data=None):
        """
        :param data: the data to parse
        :type data: dict or None
        """
        if data is None:
            data = dict()

        # Don't call ResourceResponse.__init__ as we have custom task parsing
        self.__id = data.get("id", None)
        self.__source = data.get("source", None)
        self.__created_at = data.get("created_at", None)
        self.__last_updated = data.get("last_updated", None)

        self.__lookup_profile = (
            ShareCodeProfile(data["lookup_profile"])
            if "lookup_profile" in data.keys()
            else None
        )
        self.__returned_profile = (
            ShareCodeProfile(data["returned_profile"])
            if "returned_profile" in data.keys()
            else None
        )
        self.__id_photo = (
            ShareCodeIdPhoto(data["id_photo"])
            if "id_photo" in data.keys()
            else None
        )
        self.__file = (
            FileResponse(data["file"])
            if "file" in data.keys()
            else None
        )

        # Parse tasks specifically for share code resources
        self.__tasks = [
            self.__parse_task(task) for task in data.get("tasks", [])
        ]

    @staticmethod
    def __parse_task(task):
        """
        Parse a task into a VerifyShareCodeTaskResponse

        :param task: the raw task
        :type task: dict
        :return: the parsed task
        :rtype: VerifyShareCodeTaskResponse
        """
        task_type = task.get("type", None)
        if task_type == constants.VERIFY_SHARE_CODE_TASK:
            return VerifyShareCodeTaskResponse(task)
        # Fallback to generic task response if type doesn't match
        return VerifyShareCodeTaskResponse(task)

    @property
    def id(self):
        """
        The ID of the resource

        :return: the id
        :rtype: str or None
        """
        return self.__id

    @property
    def source(self):
        """
        The source of the share code

        :return: the source
        :rtype: str or None
        """
        return self.__source

    @property
    def created_at(self):
        """
        When the share code resource was created

        :return: the created_at timestamp
        :rtype: str or None
        """
        return self.__created_at

    @property
    def last_updated(self):
        """
        When the share code resource was last updated

        :return: the last_updated timestamp
        :rtype: str or None
        """
        return self.__last_updated

    @property
    def lookup_profile(self):
        """
        The lookup profile of the share code

        :return: the lookup profile
        :rtype: ShareCodeProfile or None
        """
        return self.__lookup_profile

    @property
    def returned_profile(self):
        """
        The returned profile of the share code

        :return: the returned profile
        :rtype: ShareCodeProfile or None
        """
        return self.__returned_profile

    @property
    def id_photo(self):
        """
        The ID photo from the share code

        :return: the ID photo
        :rtype: ShareCodeIdPhoto or None
        """
        return self.__id_photo

    @property
    def file(self):
        """
        The file associated with the share code

        :return: the file
        :rtype: FileResponse or None
        """
        return self.__file

    @property
    def tasks(self):
        """
        Tasks associated with the share code resource

        :return: the list of tasks
        :rtype: list[VerifyShareCodeTaskResponse]
        """
        return self.__tasks

    @property
    def verify_share_code_tasks(self):
        """
        Returns a list of verify share code tasks associated with the share code

        :return: list of verify share code tasks
        :rtype: list[VerifyShareCodeTaskResponse]
        """
        return [
            task for task in self.tasks if isinstance(task, VerifyShareCodeTaskResponse)
        ]
