# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: EncryptedData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x45ncryptedData.proto\x12\x0c\x63ompubapi_v1\"0\n\rEncryptedData\x12\n\n\x02iv\x18\x01 \x01(\x0c\x12\x13\n\x0b\x63ipher_text\x18\x02 \x01(\x0c\x42\xe2\x01\n$com.yoti.api.client.spi.remote.protoB\x12\x45ncryptedDataProtoZ.github.com/getyoti/yoti-go-sdk/v3/yotiprotocom\xaa\x02\x19Yoti.Auth.ProtoBuf.Common\xca\x02\x17Yoti\\Protobuf\\Compubapi\xe2\x02#Yoti\\Protobuf\\Compubapi\\GPBMetadata\xea\x02\x19Yoti::Protobuf::Compubapib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'EncryptedData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n$com.yoti.api.client.spi.remote.protoB\022EncryptedDataProtoZ.github.com/getyoti/yoti-go-sdk/v3/yotiprotocom\252\002\031Yoti.Auth.ProtoBuf.Common\312\002\027Yoti\\Protobuf\\Compubapi\342\002#Yoti\\Protobuf\\Compubapi\\GPBMetadata\352\002\031Yoti::Protobuf::Compubapi'
  _ENCRYPTEDDATA._serialized_start=37
  _ENCRYPTEDDATA._serialized_end=85
# @@protoc_insertion_point(module_scope)
