# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SignedTimestamp.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15SignedTimestamp.proto\x12\x0c\x63ompubapi_v1\"\x9b\x01\n\x0fSignedTimestamp\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12\x16\n\x0emessage_digest\x18\x03 \x01(\x0c\x12\x14\n\x0c\x63hain_digest\x18\x04 \x01(\x0c\x12\x1a\n\x12\x63hain_digest_skip1\x18\x05 \x01(\x0c\x12\x1a\n\x12\x63hain_digest_skip2\x18\x06 \x01(\x0c\x42\xe4\x01\n$com.yoti.api.client.spi.remote.protoB\x14SignedTimestampProtoZ.github.com/getyoti/yoti-go-sdk/v3/yotiprotocom\xaa\x02\x19Yoti.Auth.ProtoBuf.Common\xca\x02\x17Yoti\\Protobuf\\Compubapi\xe2\x02#Yoti\\Protobuf\\Compubapi\\GPBMetadata\xea\x02\x19Yoti::Protobuf::Compubapib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SignedTimestamp_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n$com.yoti.api.client.spi.remote.protoB\024SignedTimestampProtoZ.github.com/getyoti/yoti-go-sdk/v3/yotiprotocom\252\002\031Yoti.Auth.ProtoBuf.Common\312\002\027Yoti\\Protobuf\\Compubapi\342\002#Yoti\\Protobuf\\Compubapi\\GPBMetadata\352\002\031Yoti::Protobuf::Compubapi'
  _SIGNEDTIMESTAMP._serialized_start=40
  _SIGNEDTIMESTAMP._serialized_end=195
# @@protoc_insertion_point(module_scope)
