# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ContentType.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x43ontentType.proto\x12\rattrpubapi_v1*i\n\x0b\x43ontentType\x12\r\n\tUNDEFINED\x10\x00\x12\n\n\x06STRING\x10\x01\x12\x08\n\x04JPEG\x10\x02\x12\x08\n\x04\x44\x41TE\x10\x03\x12\x07\n\x03PNG\x10\x04\x12\x08\n\x04JSON\x10\x05\x12\x0f\n\x0bMULTI_VALUE\x10\x06\x12\x07\n\x03INT\x10\x07\x42\xe7\x01\n$com.yoti.api.client.spi.remote.protoB\x10\x43ontentTypeProtoZ/github.com/getyoti/yoti-go-sdk/v3/yotiprotoattr\xaa\x02\x1cYoti.Auth.ProtoBuf.Attribute\xca\x02\x18Yoti\\Protobuf\\Attrpubapi\xe2\x02$Yoti\\Protobuf\\Attrpubapi\\GPBMetadata\xea\x02\x1aYoti::Protobuf::Attrpubapib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ContentType_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n$com.yoti.api.client.spi.remote.protoB\020ContentTypeProtoZ/github.com/getyoti/yoti-go-sdk/v3/yotiprotoattr\252\002\034Yoti.Auth.ProtoBuf.Attribute\312\002\030Yoti\\Protobuf\\Attrpubapi\342\002$Yoti\\Protobuf\\Attrpubapi\\GPBMetadata\352\002\032Yoti::Protobuf::Attrpubapi'
  _CONTENTTYPE._serialized_start=36
  _CONTENTTYPE._serialized_end=141
# @@protoc_insertion_point(module_scope)
