# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: List.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Attribute_pb2 as Attribute__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nList.proto\x12\rattrpubapi_v1\x1a\x0f\x41ttribute.proto\"S\n\x0e\x41ttributeAndId\x12+\n\tattribute\x18\x01 \x01(\x0b\x32\x18.attrpubapi_v1.Attribute\x12\x14\n\x0c\x61ttribute_id\x18\x02 \x01(\x0c\"R\n\x12\x41ttributeAndIdList\x12<\n\x15\x61ttribute_and_id_list\x18\x01 \x03(\x0b\x32\x1d.attrpubapi_v1.AttributeAndId\"=\n\rAttributeList\x12,\n\nattributes\x18\x01 \x03(\x0b\x32\x18.attrpubapi_v1.AttributeB\xe9\x01\n$com.yoti.api.client.spi.remote.protoB\x12\x41ttributeListProtoZ/github.com/getyoti/yoti-go-sdk/v3/yotiprotoattr\xaa\x02\x1cYoti.Auth.ProtoBuf.Attribute\xca\x02\x18Yoti\\Protobuf\\Attrpubapi\xe2\x02$Yoti\\Protobuf\\Attrpubapi\\GPBMetadata\xea\x02\x1aYoti::Protobuf::Attrpubapib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'List_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n$com.yoti.api.client.spi.remote.protoB\022AttributeListProtoZ/github.com/getyoti/yoti-go-sdk/v3/yotiprotoattr\252\002\034Yoti.Auth.ProtoBuf.Attribute\312\002\030Yoti\\Protobuf\\Attrpubapi\342\002$Yoti\\Protobuf\\Attrpubapi\\GPBMetadata\352\002\032Yoti::Protobuf::Attrpubapi'
  _ATTRIBUTEANDID._serialized_start=46
  _ATTRIBUTEANDID._serialized_end=129
  _ATTRIBUTEANDIDLIST._serialized_start=131
  _ATTRIBUTEANDIDLIST._serialized_end=213
  _ATTRIBUTELIST._serialized_start=215
  _ATTRIBUTELIST._serialized_end=276
# @@protoc_insertion_point(module_scope)
