# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Signing.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ContentType_pb2 as ContentType__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rSigning.proto\x12\rattrpubapi_v1\x1a\x11\x43ontentType.proto\"\xc5\x01\n\x10\x41ttributeSigning\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\x12\x30\n\x0c\x63ontent_type\x18\x03 \x01(\x0e\x32\x1a.attrpubapi_v1.ContentType\x12\x1a\n\x12\x61rtifact_signature\x18\x04 \x01(\x0c\x12\x10\n\x08sub_type\x18\x05 \x01(\t\x12\x19\n\x11signed_time_stamp\x18\x06 \x01(\x0c\x12\x19\n\x11\x61ssociated_source\x18\x07 \x01(\tB\xe3\x01\n$com.yoti.api.client.spi.remote.protoB\x0cSigningProtoZ/github.com/getyoti/yoti-go-sdk/v3/yotiprotoattr\xaa\x02\x1cYoti.Auth.ProtoBuf.Attribute\xca\x02\x18Yoti\\Protobuf\\Attrpubapi\xe2\x02$Yoti\\Protobuf\\Attrpubapi\\GPBMetadata\xea\x02\x1aYoti::Protobuf::Attrpubapib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Signing_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n$com.yoti.api.client.spi.remote.protoB\014SigningProtoZ/github.com/getyoti/yoti-go-sdk/v3/yotiprotoattr\252\002\034Yoti.Auth.ProtoBuf.Attribute\312\002\030Yoti\\Protobuf\\Attrpubapi\342\002$Yoti\\Protobuf\\Attrpubapi\\GPBMetadata\352\002\032Yoti::Protobuf::Attrpubapi'
  _ATTRIBUTESIGNING._serialized_start=52
  _ATTRIBUTESIGNING._serialized_end=249
# @@protoc_insertion_point(module_scope)
