# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: attrpubapi_v1/Unlock.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from devicepubapi_v1 import StaticCredentialAuth_pb2 as devicepubapi__v1_dot_StaticCredentialAuth__pb2
from yoti_python_sdk.protobuf.compubapi_v1 import Metadata_pb2 as compubapi__v1_dot_Metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x61ttrpubapi_v1/Unlock.proto\x12\x17yoti.core.attrpubapi_v1\x1a*devicepubapi_v1/StaticCredentialAuth.proto\x1a\x1b\x63ompubapi_v1/Metadata.proto\"\xda\x02\n\rUnlockRequest\x12\x12\n\ncredential\x18\x01 \x01(\x0c\x12\x13\n\x0bwrapped_key\x18\x02 \x01(\x0c\x12\x16\n\x0e\x61uth_data_list\x18\x03 \x01(\x0c\x12\x14\n\x0c\x61ttribute_id\x18\x04 \x01(\x0c\x12\x33\n\x0binformation\x18\x05 \x03(\x0b\x32\x1e.yoti.core.attrpubapi_v1.Entry\x12:\n\x0f\x64\x65vice_metadata\x18\xc0\x0c \x01(\x0b\x32 .yoti.core.compubapi_v1.Metadata\x12\x16\n\rfeature_flags\x18\xc1\x0c \x01(\x06\x12\x17\n\x0e\x63orrelation_id\x18\xc2\x0c \x01(\t\x12P\n\x16static_credential_auth\x18\xb8\x17 \x01(\x0b\x32/.yoti.core.devicepubapi_v1.StaticCredentialAuth\"$\n\x05\x45ntry\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\"\x93\x01\n\x0eUnlockResponse\x12>\n\x06result\x18\x01 \x01(\x0e\x32..yoti.core.attrpubapi_v1.UnlockResponse.Result\"A\n\x06Result\x12\r\n\tUNDEFINED\x10\x00\x12\x0e\n\nSUCCESSFUL\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\x12\x0c\n\x08UNLOCKED\x10\x03\x42\x64\n\x16\x63om.yoti.attrpubapi_v1B\x0bUnlockProtoZ-go.internal.yoti.com/proto/core/attrpubapi_v1\xba\x02\rAttrpubapiV1_b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Unlock_pb2.py', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026com.yoti.attrpubapi_v1B\013UnlockProtoZ-go.internal.yoti.com/proto/core/attrpubapi_v1\272\002\rAttrpubapiV1_'
  _UNLOCKREQUEST._serialized_start=129
  _UNLOCKREQUEST._serialized_end=475
  _ENTRY._serialized_start=477
  _ENTRY._serialized_end=513
  _UNLOCKRESPONSE._serialized_start=516
  _UNLOCKRESPONSE._serialized_end=663
  _UNLOCKRESPONSE_RESULT._serialized_start=598
  _UNLOCKRESPONSE_RESULT._serialized_end=663
# @@protoc_insertion_point(module_scope)
