from os import environ

YOTI_SCENARIO_ID = environ.get("YOTI_SCENARIO_ID")
YOTI_CLIENT_SDK_ID = environ.get("YOTI_CLIENT_SDK_ID")
YOTI_KEY_FILE_PATH = environ.get("YOTI_KEY_FILE_PATH")
YOTI_APPLICATION_ID = environ.get("YOTI_APPLICATION_ID")
