# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ExtraData.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import DataEntry_pb2 as DataEntry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x45xtraData.proto\x12\x0esharepubapi_v1\x1a\x0f\x44\x61taEntry.proto\"4\n\tExtraData\x12\'\n\x04list\x18\x01 \x03(\x0b\x32\x19.sharepubapi_v1.DataEntryB\xe5\x01\n$com.yoti.api.client.spi.remote.protoB\x0e\x45xtraDataProtoZ0github.com/getyoti/yoti-go-sdk/v3/yotiprotoshare\xaa\x02\x18Yoti.Auth.ProtoBuf.Share\xca\x02\x19Yoti\\Protobuf\\Sharepubapi\xe2\x02%Yoti\\Protobuf\\Sharepubapi\\GPBMetadata\xea\x02\x1bYoti::Protobuf::Sharepubapib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ExtraData_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n$com.yoti.api.client.spi.remote.protoB\016ExtraDataProtoZ0github.com/getyoti/yoti-go-sdk/v3/yotiprotoshare\252\002\030Yoti.Auth.ProtoBuf.Share\312\002\031Yoti\\Protobuf\\Sharepubapi\342\002%Yoti\\Protobuf\\Sharepubapi\\GPBMetadata\352\002\033Yoti::Protobuf::Sharepubapi'
  _EXTRADATA._serialized_start=52
  _EXTRADATA._serialized_end=104
# @@protoc_insertion_point(module_scope)
