# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IssuingAttributes.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17IssuingAttributes.proto\x12\x0esharepubapi_v1\"Y\n\x11IssuingAttributes\x12\x13\n\x0b\x65xpiry_date\x18\x01 \x01(\t\x12/\n\x0b\x64\x65\x66initions\x18\x02 \x03(\x0b\x32\x1a.sharepubapi_v1.Definition\"\x1a\n\nDefinition\x12\x0c\n\x04name\x18\x01 \x01(\tB\xed\x01\n$com.yoti.api.client.spi.remote.protoB\x16IssuingAttributesProtoZ0github.com/getyoti/yoti-go-sdk/v3/yotiprotoshare\xaa\x02\x18Yoti.Auth.ProtoBuf.Share\xca\x02\x19Yoti\\Protobuf\\Sharepubapi\xe2\x02%Yoti\\Protobuf\\Sharepubapi\\GPBMetadata\xea\x02\x1bYoti::Protobuf::Sharepubapib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'IssuingAttributes_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n$com.yoti.api.client.spi.remote.protoB\026IssuingAttributesProtoZ0github.com/getyoti/yoti-go-sdk/v3/yotiprotoshare\252\002\030Yoti.Auth.ProtoBuf.Share\312\002\031Yoti\\Protobuf\\Sharepubapi\342\002%Yoti\\Protobuf\\Sharepubapi\\GPBMetadata\352\002\033Yoti::Protobuf::Sharepubapi'
  _ISSUINGATTRIBUTES._serialized_start=43
  _ISSUINGATTRIBUTES._serialized_end=132
  _DEFINITION._serialized_start=134
  _DEFINITION._serialized_end=160
# @@protoc_insertion_point(module_scope)
