# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThirdPartyAttribute.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import IssuingAttributes_pb2 as IssuingAttributes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19ThirdPartyAttribute.proto\x12\x0esharepubapi_v1\x1a\x17IssuingAttributes.proto\"l\n\x13ThirdPartyAttribute\x12\x16\n\x0eissuance_token\x18\x01 \x01(\x0c\x12=\n\x12issuing_attributes\x18\x02 \x01(\x0b\x32!.sharepubapi_v1.IssuingAttributesB\xef\x01\n$com.yoti.api.client.spi.remote.protoB\x18ThirdPartyAttributeProtoZ0github.com/getyoti/yoti-go-sdk/v3/yotiprotoshare\xaa\x02\x18Yoti.Auth.ProtoBuf.Share\xca\x02\x19Yoti\\Protobuf\\Sharepubapi\xe2\x02%Yoti\\Protobuf\\Sharepubapi\\GPBMetadata\xea\x02\x1bYoti::Protobuf::Sharepubapib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ThirdPartyAttribute_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n$com.yoti.api.client.spi.remote.protoB\030ThirdPartyAttributeProtoZ0github.com/getyoti/yoti-go-sdk/v3/yotiprotoshare\252\002\030Yoti.Auth.ProtoBuf.Share\312\002\031Yoti\\Protobuf\\Sharepubapi\342\002%Yoti\\Protobuf\\Sharepubapi\\GPBMetadata\352\002\033Yoti::Protobuf::Sharepubapi'
  _THIRDPARTYATTRIBUTE._serialized_start=70
  _THIRDPARTYATTRIBUTE._serialized_end=178
# @@protoc_insertion_point(module_scope)
