# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ThirdPartyAttribute.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import IssuingAttributes_pb2 as IssuingAttributes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ThirdPartyAttribute.proto',
  package='sharepubapi_v1',
  syntax='proto3',
  serialized_options=_b('\n$com.yoti.api.client.spi.remote.protoB\030ThirdPartyAttributeProtoZ\016yotiprotoshare\252\002\030Yoti.Auth.ProtoBuf.Share\312\002\020Yoti\\Sharepubapi\342\002\034Yoti\\Sharepubapi\\GPBMetadata\352\002\031Yoti.Protobuf.Sharepubapi'),
  serialized_pb=_b('\n\x19ThirdPartyAttribute.proto\x12\x0esharepubapi_v1\x1a\x17IssuingAttributes.proto\"l\n\x13ThirdPartyAttribute\x12\x16\n\x0eissuance_token\x18\x01 \x01(\x0c\x12=\n\x12issuing_attributes\x18\x02 \x01(\x0b\x32!.sharepubapi_v1.IssuingAttributesB\xb9\x01\n$com.yoti.api.client.spi.remote.protoB\x18ThirdPartyAttributeProtoZ\x0eyotiprotoshare\xaa\x02\x18Yoti.Auth.ProtoBuf.Share\xca\x02\x10Yoti\\Sharepubapi\xe2\x02\x1cYoti\\Sharepubapi\\GPBMetadata\xea\x02\x19Yoti.Protobuf.Sharepubapib\x06proto3')
  ,
  dependencies=[IssuingAttributes__pb2.DESCRIPTOR,])




_THIRDPARTYATTRIBUTE = _descriptor.Descriptor(
  name='ThirdPartyAttribute',
  full_name='sharepubapi_v1.ThirdPartyAttribute',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='issuance_token', full_name='sharepubapi_v1.ThirdPartyAttribute.issuance_token', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='issuing_attributes', full_name='sharepubapi_v1.ThirdPartyAttribute.issuing_attributes', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=178,
)

_THIRDPARTYATTRIBUTE.fields_by_name['issuing_attributes'].message_type = IssuingAttributes__pb2._ISSUINGATTRIBUTES
DESCRIPTOR.message_types_by_name['ThirdPartyAttribute'] = _THIRDPARTYATTRIBUTE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ThirdPartyAttribute = _reflection.GeneratedProtocolMessageType('ThirdPartyAttribute', (_message.Message,), dict(
  DESCRIPTOR = _THIRDPARTYATTRIBUTE,
  __module__ = 'ThirdPartyAttribute_pb2'
  # @@protoc_insertion_point(class_scope:sharepubapi_v1.ThirdPartyAttribute)
  ))
_sym_db.RegisterMessage(ThirdPartyAttribute)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
