# -*- coding: utf-8 -*-
SDK_IDENTIFIER = "Python"
ATTRIBUTE_AGE_OVER = "age_over:"
ATTRIBUTE_AGE_UNDER = "age_under:"
ATTRIBUTE_POSTAL_ADDRESS = "postal_address"
ATTRIBUTE_SELFIE = "selfie"
ATTRIBUTE_STRUCTURED_POSTAL_ADDRESS = "structured_postal_address"
ATTRIBUTE_IS_AGE_VERIFIED = "is_age_verified"
ANCHOR_SOURCE = "SOURCE"
ANCHOR_VERIFIER = "VERIFIER"
KEY_FORMATTED_ADDRESS = "formatted_address"
